### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by Veason-silverbullet** [LayTextLLM/LayTextLLM#11]
”LayTextLLM projects each bounding box to a single embedding and interleaves it with text, efficiently avoiding long sequence issues while leveraging autoregressive traits of LLMs.”

Is this really your original idea?

**Comment by LayTextLLM** [comment]
Thank you for your question. Yes, the concept of LayTextLLM, which projects each bounding box to a single embedding and interleaves it with text, is indeed our original idea. As outlined in the Introduction, DocLLM avoids longer sequences but fails to leverage autoregressive traits effectively. On the other hand, approaches that treat coordinates as tokens introduce excessively long sequences, despite utilizing autoregressive capabilities. LayTextLLM addresses these issues by combining the strengths of both approaches, ensuring efficiency in sequence handling while fully utilizing the autoregressive nature of LLMs.

**Comment by Veason-silverbullet** [comment]
@LayTextLLM I don't think so. See https://aclanthology.org/2024.naacl-long.264

**Comment by LayTextLLM** [comment]
Thank you for bringing up that reference. After reviewing the paper, there are significant differences between LayTextLLM and ViTLP.

For example, in LayTextLLM, we directly project from 4 to d-dimension using a linear projector, whereas ViTLP utilizes d/4 dimension for each of the four coordinates, followed by concatenation. This results in a fundamentally different implementation.

Additionally, the two approaches diverge in terms of model architecture (LLM vs. a model trained from scratch), input modalities, training methodologies, and other key aspects. Nonetheless, we acknowledge the reference and will include it in the related work section in the updated version of our paper.
