### ISSUE TITLE
Requesting for Training script

### ISSUE THREAD

**Issue by adnanPBI** [LayTextLLM/LayTextLLM#12]
Hi,
Could you please share the train.py script as I want to work on this LLM for
structured document parsing.

Regards,
Adnan

**Comment by hubin1108** [comment]
very good project, I want it too.

**Comment by adnanPBI** [comment]
I have worked with tesseract+LayoutLMv3 for kay-value extraction but now I
do want to apply your LayTextLLM with OCR tool for structured data parsing
operations.

**Comment by LayTextLLM** [comment]
Hi everyone, we are delighted to release the training code with Deepspeed and Huggingface Trainer, please check the update repo and readme,  thanks for the patience and waiting.
