### ISSUE TITLE
LNTP为什么更新SLP and P-LoRA的参数？

### ISSUE THREAD

**Issue by dbcSep03** [LayTextLLM/LayTextLLM#13]
文章写道LNTP只计算文本的预测loss?这样的话文本并没有经过SLP和P-LoRA的参数？为什么两者参数能更新，谢谢！

**Comment by LayTextLLM** [comment]
尽管损失不是直接针对坐标计算的，但SLP仍然得到了有效训练。在图3(b) 中，t2的预测依赖于b1的隐藏状态，使得监督信号能够反向传播到SLP和P-LoRA。
