### ISSUE TITLE
Request for Dataset preparation

### ISSUE THREAD

**Issue by adnanPBI** [LayTextLLM/LayTextLLM#14]
Hi,

Many thanks for the training script. Can you please provide another support to provide guidance for dataset preparation of FUNSD & CORD datasets?

Regards,
Adnan

**Comment by LayTextLLM** [comment]
Hi,

Please check the Constructing Your Own Dataset Set of the latest readme, thanks for the support.

**Comment by adnanPBI** [comment]
Hi,

I have seen your "Constructing dataset" on readme but it shows only output format which is in json but I requested you how I shall annotate input images, add label and python script for the json output from annotated images.

Thank you.

**Comment by LayTextLLM** [comment]
I would recommend PaddleOCR(https://github.com/PaddlePaddle/PaddleOCR) or MMOCR(https://github.com/open-mmlab/mmocr) to extract ocr text and corresponding coordinates.

**Comment by adnanPBI** [comment]
Can you please provide a specific guide about how I shall annotate a
typical table and receipt and then json file of the annotated data?

**Comment by LayTextLLM** [comment]
Once using OCR to extract the text and corresponding coordinates, you can format them like json files provided in dir datasets, such as funsd_train.json

**Comment by adnanPBI** [comment]
I apologize for my recurrent interruptions regarding dataset help, if you
could provide some screenshots of the dataset preparations that would help
me greatly. I wanted to train scanned money receipt data with your model,
that's why I'm asking you.

**Comment by LayTextLLM** [comment]
Hi, we have updated a example construction script in `datasets/laytextllm_construct_example.py`, enjoy the code.

**Comment by adnanPBI** [comment]
Thanks, I'll check it out.
