### ISSUE TITLE
Questions about inference

### ISSUE THREAD

**Issue by zhuangxy** [LayTextLLM/LayTextLLM#7]
请问datasets目录下的test data是如何生成的？如果有一张自己的图表，如果使用LayTextLLM做inference? 谢谢

**Comment by LayTextLLM** [comment]
You should use an OCR tool to scan your chart. The extracted OCR text should be placed under the "ocr" key, while the corresponding OCR coordinates should be stored under the "poly" key. The image size should be stored in "img_size" key as shown below:

{
  "ocr": [
    "Text 1",
    "Text 2",
    "Text 3"
  ],
  "poly": [
    [x1, y1, x2, y2, x3, y3, x4, y4],
    [x1, y1, x2, y2, x3, y3, x4, y4],
    [x1, y1, x2, y2, x3, y3, x4, y4],
  ],
"img_size": {
            "h": height_of_img,
            "w": width_of_img
        },
}

**Comment by zhuangxy** [comment]
Hi @LayTextLLM ,

Thank you for your response. Is there an OCR tool recommended? I'm not very familiar with OCR techs, and there are so many search results..

**Comment by LayTextLLM** [comment]
I would recommend PaddleOCR(https://github.com/PaddlePaddle/PaddleOCR) or MMOCR(https://github.com/open-mmlab/mmocr).
