### ISSUE TITLE
是否支持中文

### ISSUE THREAD

**Issue by suhu753** [LayTextLLM/LayTextLLM#8]
是否有支持中文码表的模型？

**Comment by LayTextLLM** [comment]
While we currently do not plan to release a Chinese model, you can replicate one following the approach described in the paper using Baichuan2 or Qwen2. Our internal testing on in-house datasets has shown that the LayText method can be effectively adapted to Chinese data.

**Comment by suhu753** [comment]
ok, thank you!

**Comment by l1006986533** [comment]
刚刚测试了一下中文，如果按照英文格式询问中文内容，是可以的。例如："What is the content in the 姓名 field?"，回答："张三"。但中文问答不行，例如：“这张表格中申请人的姓名是？”，就会回答英文。
I just tested in Chinese and found out that, if you ask Chinese field in English format, like "What is the content in the 姓名 field?", it can answer correctly. But if your question is totally in Chinese, like “这张表格中申请人的姓名是？”, then it answers wrongly.
