### ISSUE TITLE
Bounding box coordinates in response

### ISSUE THREAD

**Issue by JamesQuirk** [LayTextLLM/LayTextLLM#9]
How do you get the model to respond with bounding box coordinates as well as the answer?

**Comment by suhu753** [comment]
In the inference stage, I found that the predicted results were often marked boxes that were very close to the target area.

**Comment by LayTextLLM** [comment]
The released version is not specifically designed to predict bounding boxes; we only expect it to predict text. However, LayTextLLM Zero was trained using the Document Dense Description (DDD) dataset, which includes some responses containing bounding boxes. We believe this is where the model’s ability to predict bounding boxes originates. Additionally, we trained an in-house version explicitly designed to predict text along with bounding boxes. The results of this can be found in the Appendix.

**Comment by LayTextLLM** [comment]
Hi everyone, please check the latest readme regarding how converting bounding box tokens to coordinates, thanks for the support.
